---
title: "20220819_workflow: integrate spatial transcriptome and Image Mouse_Brain_Serial_Section1_SagittalPosterior"
author: "Yu Wang, Shilin Zhao"
date: "08/19/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, message = F, warning = F}
require(tidyverse)
require(Seurat)
#require(CellID)
#require(SingleR)
require(stImage)
require(patchwork)
require(Cairo)
require(reticulate)
use_condaenv("myenv")
#install_tensorflow()
require(tensorflow)
require(keras)

new_tstamp <- gsub("-", "", as.character(Sys.Date()))
new_tstamp <- "20220819"
tstamp <- "20220526"
#source("/data/cqs/ywang/Zhao_image/stImage/SpatialTranscriptomicsImage/stImage/ImageFeature_rawImage.R")
#source("/data/cqs/ywang/Zhao_image/stImage/SpatialTranscriptomicsImage/stImage/LoadImageFeature.R")
#source("/data/cqs/ywang/Zhao_image/stImage/SpatialTranscriptomicsImage/stImage/MultimodalImageWorkflow.R")


```

```{r}
pre_path = "/data/cqs/ywang/Zhao_image/stImage"
proj_folder = "Mouse_Brain_Serial_Section1_SagittalPosterior"
workDir = paste(pre_path, "SpatialTranscriptomicsImage", "stImage", sep = "/")
h5_file = "V1_Mouse_Brain_Sagittal_Posterior_filtered_feature_bc_matrix.h5"
setwd(workDir)

data_path=paste(pre_path, proj_folder, sep = "/") #need filtered_feature_bc_matrix.h5 file and spatial folder
spatial_path = paste(data_path, "spatial", sep = "/")

imgFile=paste(spatial_path, "tissue_hires_image.png", sep = "/")
rawimg=paste(data_path, "V1_Mouse_Brain_Sagittal_Posterior_image.tif", sep = "/")

#positionTableFile is 10X format, Columns: Tissue; Y,X,ImageY,ImageX
positionTableFile=paste(spatial_path, "tissue_positions_list.csv", sep = "/")

patchSize=200

```

# load our Mouse_Brain_Serial_Section1_SagittalPosterior object (raw image version)

```{r}
#Mouse_Brain_Serial_Section1_SagittalPosterior_rawimage_obj <- readRDS("Mouse_Brain_Serial_Section1_SagittalPosterior_rawimage_object.rds")
Mouse_Brain_Serial_Section1_SagittalPosterior_rawimage_obj <- readRDS(paste0(workDir, "/", proj_folder, "_rawimage_object", tstamp, ".rds"))

```

# run analysis with stLearn and Yuankai's imagefeature data


```{r, eval=FALSE}
imageFeatures_stLearn <- read.csv(paste0(workDir,"/Yuankai/SagittalPosterior_S1_imagefeature_stLearn.csv"), row.names=1)
imageFeatures_stLearn[is.na(imageFeatures_stLearn)] <- 0

imageFeaturePCs_stLearn <- read.csv(paste0(workDir,"/Yuankai/SagittalPosterior_S1_imagefeaturePCs_stLearn.csv"), row.names=1)
imageFeaturePCs_stLearn <- as.matrix(imageFeaturePCs_stLearn)

SagittalPosterior_S1_stLearn_obj <- LoadImageFeatureVisium(data_path, filename = h5_file,
                                  imageFeatures = imageFeatures_stLearn)

imageFeatures_Yuankai <- read.csv(paste0(workDir,"/Yuankai/SagittalPosterior_S1_imagefeature_Yuankai_fix.csv"), row.names=1)
imageFeatures_Yuankai[is.na(imageFeatures_Yuankai)] <- 0

SagittalPosterior_S1_Yuankai_obj <- LoadImageFeatureVisium(data_path, filename = h5_file,
                                  imageFeatures = imageFeatures_Yuankai)

imageFeatures_MUSE <- read.csv(paste0(workDir,"/Yuankai/SagittalPosterior_S1_imagefeature_MUSE_fix.csv"), row.names=1)
#imageFeatures_MUSE[is.na(imageFeatures_Yuankai)] <- 0

SagittalPosterior_S1_MUSE_obj <- LoadImageFeatureVisium(data_path, filename = h5_file,
                                  imageFeatures = imageFeatures_MUSE)

##resnet50 Yuankai's version
imageFeatures_Yuankai_resnet50 <- read.csv(paste0(workDir,"/Yuankai/20220805/clustering_data_Resnet50/1_feature_resnet50.csv"), row.names=1)
imageFeatures_Yuankai_resnet50 <- imageFeatures_Yuankai_resnet50[,-(1:3)]
colnames(imageFeatures_Yuankai_resnet50) <- paste0("ImageFeature", as.numeric(gsub("X(\\d+)$", "\\1", colnames(imageFeatures_Yuankai_resnet50))) + 1)
imageFeatures_Yuankai_resnet50 <- imageFeatures_Yuankai_resnet50[order(rownames(imageFeatures_Yuankai_resnet50)),]
SagittalPosterior_S1_Yuankai_resnet50_obj <- LoadImageFeatureVisium(data_path, filename = h5_file,
                                  imageFeatures = imageFeatures_Yuankai_resnet50)

##vgg16 Yuankai's version
imageFeatures_Yuankai_vgg16 <- read.csv(paste0(workDir,"/Yuankai/20220805/clustering_data_vgg16/1_feature_vgg16.csv"), row.names=1)
imageFeatures_Yuankai_vgg16 <- imageFeatures_Yuankai_vgg16[,-(1:3)]
colnames(imageFeatures_Yuankai_vgg16) <- paste0("ImageFeature", as.numeric(gsub("X(\\d+)$", "\\1", colnames(imageFeatures_Yuankai_vgg16))) + 1)
imageFeatures_Yuankai_vgg16 <- imageFeatures_Yuankai_vgg16[order(rownames(imageFeatures_Yuankai_vgg16)),]
SagittalPosterior_S1_Yuankai_vgg16_obj <- LoadImageFeatureVisium(data_path, filename = h5_file,
                                  imageFeatures = imageFeatures_Yuankai_vgg16)

```

## Data preprocessing of Spatial matrix and ImageFeature matrix

```{r, eval = F}
SagittalPosterior_S1_stLearnPC_obj <- CreateDimReducObject(embeddings = imageFeaturePCs_stLearn, key = "iPC_", assay = "ImageFeature")
SagittalPosterior_S1_stLearn_obj <- MultimodalPreProcess(SagittalPosterior_S1_stLearn_obj, normalizeMethod = "SCT", ImageFeaturePCobj = SagittalPosterior_S1_stLearnPC_obj, pcaDim_s=30, pcaDim_i=30, geneResolution=0.9, imageFeatureResolution=1.7)
#DoHeatmap(SagittalPosterior_S1_stLearn_obj, assay="ImageFeature")
saveRDS(SagittalPosterior_S1_stLearn_obj, paste0(proj_folder, "_stLearn_object", new_tstamp, ".rds"))
#SagittalPosterior_S1_stLearn_obj <- readRDS(paste0(proj_folder, "_stLearn_object", new_tstamp, ".rds"))

SagittalPosterior_S1_Yuankai_obj <- MultimodalPreProcess(SagittalPosterior_S1_Yuankai_obj, normalizeMethod = "SCT", pcaDim_s=30, pcaDim_i=30, geneResolution=0.9, imageFeatureResolution=1.7)
#DoHeatmap(SagittalPosterior_S1_stLearn_obj, assay="ImageFeature")
saveRDS(SagittalPosterior_S1_Yuankai_obj, paste0(proj_folder, "_Yuankai_object", new_tstamp, ".rds"))
#SagittalPosterior_S1_Yuankai_obj <- readRDS(paste0(proj_folder, "_Yuankai_object", new_tstamp, ".rds"))

SagittalPosterior_S1_MUSE_obj <- MultimodalPreProcess(SagittalPosterior_S1_MUSE_obj, normalizeMethod = "SCT", pcaDim_s=30, pcaDim_i=30, geneResolution=0.9, imageFeatureResolution=1.7)
#DoHeatmap(SagittalPosterior_S1_stLearn_obj, assay="ImageFeature")
saveRDS(SagittalPosterior_S1_MUSE_obj, paste0(proj_folder, "_MUSE_object", new_tstamp, ".rds"))


SagittalPosterior_S1_Yuankai_resnet50_obj <- MultimodalPreProcess(SagittalPosterior_S1_Yuankai_resnet50_obj, normalizeMethod = "SCT", pcaDim_s=30, pcaDim_i=30, geneResolution=0.9, imageFeatureResolution=1.7)
#DoHeatmap(SagittalPosterior_S1_stLearn_obj, assay="ImageFeature")
saveRDS(SagittalPosterior_S1_Yuankai_resnet50_obj, paste0(proj_folder, "_Yuankai_resnet50_object", new_tstamp, ".rds"))
#SagittalPosterior_S1_Yuankai_resnet50_obj <- readRDS(paste0(proj_folder, "_Yuankai_resnet50_object", new_tstamp, ".rds"))


SagittalPosterior_S1_Yuankai_vgg16_obj <- MultimodalPreProcess(SagittalPosterior_S1_Yuankai_vgg16_obj, normalizeMethod = "SCT", pcaDim_s=30, pcaDim_i=30, geneResolution=0.9, imageFeatureResolution=1.7)
#DoHeatmap(SagittalPosterior_S1_stLearn_obj, assay="ImageFeature")
saveRDS(SagittalPosterior_S1_Yuankai_vgg16_obj, paste0(proj_folder, "_Yuankai_vgg16_object", new_tstamp, ".rds"))
#SagittalPosterior_S1_Yuankai_vgg16_obj <- readRDS(paste0(proj_folder, "_Yuankai_vgg16_object", new_tstamp, ".rds"))

```

## Data analysis of Spatial matrix and ImageFeature matrix

```{r, eval = F}
SagittalPosterior_S1_stLearn_obj <- MultiModalIntegrationVisium(SagittalPosterior_S1_stLearn_obj, normalizeMethod = "SCT", pcaDim_s=30, pcaDim_i=30, imageAndGeneResolution=0.7, MultimodalMethod = c("WNN"))
#DoHeatmap(SagittalPosterior_S1_stLearn_obj, assay="ImageFeature")
saveRDS(SagittalPosterior_S1_stLearn_obj, paste0(proj_folder, "_stLearn_object", new_tstamp, ".rds"))
#SagittalPosterior_S1_stLearn_obj <- readRDS(paste0(proj_folder, "_stLearn_object", new_tstamp, ".rds"))

SagittalPosterior_S1_Yuankai_obj <- MultiModalIntegrationVisium(SagittalPosterior_S1_Yuankai_obj, normalizeMethod = "SCT", pcaDim_s=30, pcaDim_i=30, imageAndGeneResolution=0.7, MultimodalMethod = c("WNN"))
#DoHeatmap(SagittalPosterior_S1_stLearn_obj, assay="ImageFeature")
saveRDS(SagittalPosterior_S1_Yuankai_obj, paste0(proj_folder, "_Yuankai_object", new_tstamp, ".rds"))
#SagittalPosterior_S1_Yuankai_obj <- readRDS(paste0(proj_folder, "_Yuankai_object", new_tstamp, ".rds"))

SagittalPosterior_S1_MUSE_obj <- MultiModalIntegrationVisium(SagittalPosterior_S1_MUSE_obj, normalizeMethod = "SCT", pcaDim_s=30, pcaDim_i=30, imageAndGeneResolution=0.7, MultimodalMethod = c("WNN"))
#DoHeatmap(SagittalPosterior_S1_stLearn_obj, assay="ImageFeature")
saveRDS(SagittalPosterior_S1_MUSE_obj, paste0(proj_folder, "_MUSE_object", new_tstamp, ".rds"))
#SagittalPosterior_S1_Yuankai_obj <- readRDS(paste0(proj_folder, "_Yuankai_object", new_tstamp, ".rds"))

SagittalPosterior_S1_Yuankai_resnet50_obj <- MultiModalIntegrationVisium(SagittalPosterior_S1_Yuankai_resnet50_obj, normalizeMethod = "SCT", pcaDim_s=30, pcaDim_i=30, imageAndGeneResolution=0.7, MultimodalMethod = c("WNN"))
#DoHeatmap(SagittalPosterior_S1_stLearn_obj, assay="ImageFeature")
saveRDS(SagittalPosterior_S1_Yuankai_obj, paste0(proj_folder, "_Yuankai_resnet50_object", new_tstamp, ".rds"))
#SagittalPosterior_S1_Yuankai_obj <- readRDS(paste0(proj_folder, "_Yuankai_object", new_tstamp, ".rds"))

SagittalPosterior_S1_Yuankai_vgg16_obj <- MultiModalIntegrationVisium(SagittalPosterior_S1_Yuankai_vgg16_obj, normalizeMethod = "SCT", pcaDim_s=30, pcaDim_i=30, imageAndGeneResolution=0.7, MultimodalMethod = c("WNN"))
#DoHeatmap(SagittalPosterior_S1_stLearn_obj, assay="ImageFeature")
saveRDS(SagittalPosterior_S1_Yuankai_vgg16_obj, paste0(proj_folder, "_Yuankai_vgg16_object", new_tstamp, ".rds"))
#SagittalPosterior_S1_Yuankai_obj <- readRDS(paste0(proj_folder, "_Yuankai_object", new_tstamp, ".rds"))

```


```{r}
SagittalPosterior_S1_stLearn_obj <- readRDS(paste0(proj_folder, "_stLearn_object", new_tstamp, ".rds"))
SagittalPosterior_S1_Yuankai_obj <- readRDS(paste0(proj_folder, "_Yuankai_object", new_tstamp, ".rds"))
SagittalPosterior_S1_MUSE_obj <- readRDS(paste0(proj_folder, "_MUSE_object", new_tstamp, ".rds"))
SagittalPosterior_S1_Yuankai_resnet50_obj <- readRDS(paste0(proj_folder, "_Yuankai_resnet50_object", new_tstamp, ".rds"))
SagittalPosterior_S1_Yuankai_vgg16_obj <- readRDS(paste0(proj_folder, "_Yuankai_vgg16_object", new_tstamp, ".rds"))
```

## plot


### SpatialDimPlot

```{r, warning = F, fig.dim = c(12, 30)}
DefaultAssay(Mouse_Brain_Serial_Section1_SagittalPosterior_rawimage_obj) <- "Spatial"
p1 <- SpatialDimPlot(Mouse_Brain_Serial_Section1_SagittalPosterior_rawimage_obj, group.by = "SCT_snn_res.0.9", alpha = 0.8, pt.size.factor = 1.5, label = TRUE, label.box = F, label.size = 4) + ggtitle(paste("Our method", "Gene Expression", sep = "\n")) & NoLegend()

DefaultAssay(Mouse_Brain_Serial_Section1_SagittalPosterior_rawimage_obj) <- "ImageFeature"
p2 <- SpatialDimPlot(Mouse_Brain_Serial_Section1_SagittalPosterior_rawimage_obj, group.by = "ImageFeature_snn_res.1.7", alpha = 0.8, pt.size.factor = 1.5, label = TRUE, label.box = F, label.size = 4) + ggtitle(paste("Our method", "Image Feature", sep = "\n")) & NoLegend()

p3 <- SpatialDimPlot(Mouse_Brain_Serial_Section1_SagittalPosterior_rawimage_obj, group.by = "wsnn_res.0.7", alpha = 0.8, pt.size.factor = 1.5, label = TRUE, label.box = F, repel = TRUE, label.size = 4) + ggtitle(paste("Our method", "WNN", sep = "\n")) & NoLegend()

DefaultAssay(SagittalPosterior_S1_stLearn_obj) <- "Spatial"
p4 <- SpatialDimPlot(SagittalPosterior_S1_stLearn_obj, group.by = "SCT_snn_res.0.9", alpha = 0.8, pt.size.factor = 1.5, label = TRUE, label.box = F, label.size = 4) + ggtitle(paste("stLearn", "Gene Expression", sep = "\n")) & NoLegend()

DefaultAssay(SagittalPosterior_S1_stLearn_obj) <- "ImageFeature"
p5 <- SpatialDimPlot(SagittalPosterior_S1_stLearn_obj, group.by = "ImageFeature_snn_res.1.7", alpha = 0.8, pt.size.factor = 1.5, label = TRUE, label.box = F, label.size = 4) + ggtitle(paste("stLearn", "Image Feature", sep = "\n")) & NoLegend()

p6 <- SpatialDimPlot(SagittalPosterior_S1_stLearn_obj, group.by = "wsnn_res.0.7", alpha = 0.8, pt.size.factor = 1.5, label = TRUE, label.box = F, repel = TRUE, label.size = 4) + ggtitle(paste("stLearn", "WNN", sep = "\n")) & NoLegend()

DefaultAssay(SagittalPosterior_S1_Yuankai_obj) <- "Spatial"
p7 <- SpatialDimPlot(SagittalPosterior_S1_Yuankai_obj, group.by = "SCT_snn_res.0.9", alpha = 0.8, pt.size.factor = 1.5, label = TRUE, label.box = F, label.size = 4) + ggtitle(paste("Yuankai", "Gene Expression", sep = "\n")) & NoLegend()

DefaultAssay(SagittalPosterior_S1_Yuankai_obj) <- "ImageFeature"
p8 <- SpatialDimPlot(SagittalPosterior_S1_Yuankai_obj, group.by = "ImageFeature_snn_res.1.7", alpha = 0.8, pt.size.factor = 1.5, label = TRUE, label.box = F, label.size = 4) + ggtitle(paste("Yuankai", "Image Feature", sep = "\n")) & NoLegend()

p9 <- SpatialDimPlot(SagittalPosterior_S1_Yuankai_obj, group.by = "wsnn_res.0.7", alpha = 0.8, pt.size.factor = 1.5, label = TRUE, label.box = F, repel = TRUE, label.size = 4) + ggtitle(paste("Yuankai", "WNN", sep = "\n")) & NoLegend()

DefaultAssay(SagittalPosterior_S1_MUSE_obj) <- "Spatial"
p10 <- SpatialDimPlot(SagittalPosterior_S1_MUSE_obj, group.by = "SCT_snn_res.0.9", alpha = 0.8, pt.size.factor = 1.5, label = TRUE, label.box = F, label.size = 4) + ggtitle(paste("MUSE", "Gene Expression", sep = "\n")) & NoLegend()

DefaultAssay(SagittalPosterior_S1_MUSE_obj) <- "ImageFeature"
p11 <- SpatialDimPlot(SagittalPosterior_S1_MUSE_obj, group.by = "ImageFeature_snn_res.1.7", alpha = 0.8, pt.size.factor = 1.5, label = TRUE, label.box = F, label.size = 4) + ggtitle(paste("MUSE", "Image Feature", sep = "\n")) & NoLegend()

p12 <- SpatialDimPlot(SagittalPosterior_S1_MUSE_obj, group.by = "wsnn_res.0.7", alpha = 0.8, pt.size.factor = 1.5, label = TRUE, label.box = F, repel = TRUE, label.size = 4) + ggtitle(paste("MUSE", "WNN", sep = "\n")) & NoLegend()

DefaultAssay(SagittalPosterior_S1_Yuankai_resnet50_obj) <- "Spatial"
p13 <- SpatialDimPlot(SagittalPosterior_S1_Yuankai_resnet50_obj, group.by = "SCT_snn_res.0.9", alpha = 0.8, pt.size.factor = 1.5, label = TRUE, label.box = F, label.size = 4) + ggtitle(paste("Yuankai_resnet50", "Gene Expression", sep = "\n")) & NoLegend()

DefaultAssay(SagittalPosterior_S1_Yuankai_resnet50_obj) <- "ImageFeature"
p14 <- SpatialDimPlot(SagittalPosterior_S1_Yuankai_resnet50_obj, group.by = "ImageFeature_snn_res.1.7", alpha = 0.8, pt.size.factor = 1.5, label = TRUE, label.box = F, label.size = 4) + ggtitle(paste("Yuankai_resnet50", "Image Feature", sep = "\n")) & NoLegend()

p15 <- SpatialDimPlot(SagittalPosterior_S1_Yuankai_resnet50_obj, group.by = "wsnn_res.0.7", alpha = 0.8, pt.size.factor = 1.5, label = TRUE, label.box = F, repel = TRUE, label.size = 4) + ggtitle(paste("Yuankai_resnet50", "WNN", sep = "\n")) & NoLegend()

DefaultAssay(SagittalPosterior_S1_Yuankai_vgg16_obj) <- "Spatial"
p16 <- SpatialDimPlot(SagittalPosterior_S1_Yuankai_vgg16_obj, group.by = "SCT_snn_res.0.9", alpha = 0.8, pt.size.factor = 1.5, label = TRUE, label.box = F, label.size = 4) + ggtitle(paste("Yuankai_vgg16", "Gene Expression", sep = "\n")) & NoLegend()

DefaultAssay(SagittalPosterior_S1_Yuankai_vgg16_obj) <- "ImageFeature"
p17 <- SpatialDimPlot(SagittalPosterior_S1_Yuankai_vgg16_obj, group.by = "ImageFeature_snn_res.1.7", alpha = 0.8, pt.size.factor = 1.5, label = TRUE, label.box = F, label.size = 4) + ggtitle(paste("Yuankai_vgg16", "Image Feature", sep = "\n")) & NoLegend()

p18 <- SpatialDimPlot(SagittalPosterior_S1_Yuankai_vgg16_obj, group.by = "wsnn_res.0.7", alpha = 0.8, pt.size.factor = 1.5, label = TRUE, label.box = F, repel = TRUE, label.size = 4) + ggtitle(paste("Yuankai_vgg16", "WNN", sep = "\n")) & NoLegend()

p1 + p2 + p3 + p4 + p5 + p6 + p7 + p8 + p9 + p10 + p11 + p12 + p13 + p14 + p15 + p16 + p17 + p18 + plot_layout(ncol = 3)
```


```{r, eval = F}
CairoPDF("Mouse_Brain_Serial_Section1_SagittalPosterior_rawimage_comparison_obj_SpatialDimPlots.pdf", width = 12, height = 30, onefile = T)
p1 + p2 + p3 + p4 + p5 + p6 + p7 + p8 + p9 + p10 + p11 + p12 + p13 + p14 + p15 + p16 + p17 + p18 + plot_layout(ncol = 3)
dev.off()
```

```{r, warning = F, fig.dim = c(20, 40)}
DefaultAssay(Mouse_Brain_Serial_Section1_SagittalPosterior_rawimage_obj) <- "ImageFeature"
Mouse_Brain_Serial_Section1_SagittalPosterior_rawimage_obj <- AddMetaData(object = Mouse_Brain_Serial_Section1_SagittalPosterior_rawimage_obj, metadata = as.data.frame(Mouse_Brain_Serial_Section1_SagittalPosterior_rawimage_obj@reductions$ipca@cell.embeddings))
DefaultAssay(SagittalPosterior_S1_stLearn_obj) <- "ImageFeature"
SagittalPosterior_S1_stLearn_obj <- AddMetaData(object = SagittalPosterior_S1_stLearn_obj, metadata = as.data.frame(SagittalPosterior_S1_stLearn_obj@reductions$ipca@cell.embeddings))
DefaultAssay(SagittalPosterior_S1_Yuankai_obj) <- "ImageFeature"
SagittalPosterior_S1_Yuankai_obj <- AddMetaData(object = SagittalPosterior_S1_Yuankai_obj, metadata = as.data.frame(SagittalPosterior_S1_Yuankai_obj@reductions$ipca@cell.embeddings))
DefaultAssay(SagittalPosterior_S1_MUSE_obj) <- "ImageFeature"
SagittalPosterior_S1_MUSE_obj <- AddMetaData(object = SagittalPosterior_S1_MUSE_obj, metadata = as.data.frame(SagittalPosterior_S1_MUSE_obj@reductions$ipca@cell.embeddings))
DefaultAssay(SagittalPosterior_S1_Yuankai_resnet50_obj) <- "ImageFeature"
SagittalPosterior_S1_Yuankai_resnet50_obj <- AddMetaData(object = SagittalPosterior_S1_Yuankai_resnet50_obj, metadata = as.data.frame(SagittalPosterior_S1_Yuankai_resnet50_obj@reductions$ipca@cell.embeddings))
DefaultAssay(SagittalPosterior_S1_Yuankai_vgg16_obj) <- "ImageFeature"
SagittalPosterior_S1_Yuankai_vgg16_obj <- AddMetaData(object = SagittalPosterior_S1_Yuankai_vgg16_obj, metadata = as.data.frame(SagittalPosterior_S1_Yuankai_vgg16_obj@reductions$ipca@cell.embeddings))


CairoPDF("SagittalPosterior_S1_rawimage_comparison_obj_ImageFeaturePCs.pdf", width = 20, height = 40, onefile = T)
SpatialFeaturePlot(Mouse_Brain_Serial_Section1_SagittalPosterior_rawimage_obj, features = colnames(Mouse_Brain_Serial_Section1_SagittalPosterior_rawimage_obj@reductions$ipca@cell.embeddings), pt.size.factor = 1.6, alpha = c(0.01, 1), ncol = 5)

SpatialFeaturePlot(SagittalPosterior_S1_stLearn_obj, features = colnames(SagittalPosterior_S1_stLearn_obj@reductions$ipca@cell.embeddings), pt.size.factor = 1.6, alpha = c(0.01, 1), ncol = 5)

SpatialFeaturePlot(SagittalPosterior_S1_Yuankai_obj, features = colnames(SagittalPosterior_S1_Yuankai_obj@reductions$ipca@cell.embeddings), pt.size.factor = 1.6, alpha = c(0.01, 1), ncol = 5)

SpatialFeaturePlot(SagittalPosterior_S1_MUSE_obj, features = colnames(SagittalPosterior_S1_MUSE_obj@reductions$ipca@cell.embeddings), pt.size.factor = 1.6, alpha = c(0.01, 1), ncol = 5)

SpatialFeaturePlot(SagittalPosterior_S1_Yuankai_resnet50_obj, features = colnames(SagittalPosterior_S1_Yuankai_resnet50_obj@reductions$ipca@cell.embeddings), pt.size.factor = 1.6, alpha = c(0.01, 1), ncol = 5)


SpatialFeaturePlot(SagittalPosterior_S1_Yuankai_vgg16_obj, features = colnames(SagittalPosterior_S1_Yuankai_vgg16_obj@reductions$ipca@cell.embeddings), pt.size.factor = 1.6, alpha = c(0.01, 1), ncol = 5)

dev.off()

```

### Weight of SCT and ImageFeature

```{r, warning = F, fig.dim = c(8, 21)}

p20 <- VlnPlot(Mouse_Brain_Serial_Section1_SagittalPosterior_rawimage_obj, features = "SCT.weight", group.by = 'wsnn_res.0.7', sort = TRUE, pt.size = 0.1) +
  NoLegend()
p21 <- VlnPlot(Mouse_Brain_Serial_Section1_SagittalPosterior_rawimage_obj, features = "ImageFeature.weight", group.by = 'wsnn_res.0.7', sort = TRUE, pt.size = 0.1) +
  NoLegend()

p22 <- VlnPlot(SagittalPosterior_S1_stLearn_obj, features = "SCT.weight", group.by = 'wsnn_res.0.7', sort = TRUE, pt.size = 0.1) +
  NoLegend()
p23 <- VlnPlot(SagittalPosterior_S1_stLearn_obj, features = "ImageFeature.weight", group.by = 'wsnn_res.0.7', sort = TRUE, pt.size = 0.1) +
  NoLegend()

p24 <- VlnPlot(SagittalPosterior_S1_Yuankai_obj, features = "SCT.weight", group.by = 'wsnn_res.0.7', sort = TRUE, pt.size = 0.1) +
  NoLegend()
p25 <- VlnPlot(SagittalPosterior_S1_Yuankai_obj, features = "ImageFeature.weight", group.by = 'wsnn_res.0.7', sort = TRUE, pt.size = 0.1) +
  NoLegend()

p26 <- VlnPlot(SagittalPosterior_S1_MUSE_obj, features = "SCT.weight", group.by = 'wsnn_res.0.7', sort = TRUE, pt.size = 0.1) +
  NoLegend()
p27 <- VlnPlot(SagittalPosterior_S1_MUSE_obj, features = "ImageFeature.weight", group.by = 'wsnn_res.0.7', sort = TRUE, pt.size = 0.1) +
  NoLegend()

p28 <- VlnPlot(SagittalPosterior_S1_Yuankai_resnet50_obj, features = "SCT.weight", group.by = 'wsnn_res.0.7', sort = TRUE, pt.size = 0.1) +
  NoLegend()
p29 <- VlnPlot(SagittalPosterior_S1_Yuankai_resnet50_obj, features = "ImageFeature.weight", group.by = 'wsnn_res.0.7', sort = TRUE, pt.size = 0.1) +
  NoLegend()

p30 <- VlnPlot(SagittalPosterior_S1_Yuankai_vgg16_obj, features = "SCT.weight", group.by = 'wsnn_res.0.7', sort = TRUE, pt.size = 0.1) +
  NoLegend()
p31 <- VlnPlot(SagittalPosterior_S1_Yuankai_vgg16_obj, features = "ImageFeature.weight", group.by = 'wsnn_res.0.7', sort = TRUE, pt.size = 0.1) +
  NoLegend()


p20 + p21 + p22 + p23 + p24 + p25 + p26 + p27 + p28 + p29 + p30 + p31
```

