---
title: "integrate spatial transcriptome and Image with stImage (Adult_Mouse_Olfactory_Bulb)"
output:
  html_document:
    theme: united
    df_print: kable
  pdf_document: default
date: 'Compiled: `r Sys.Date()`'
---

```{r setup, include=FALSE}
all_times <- list()  # store the time for each chunk
knitr::knit_hooks$set(time_it = local({
  now <- NULL
  function(before, options) {
    if (before) {
      now <<- Sys.time()
    } else {
      res <- difftime(Sys.time(), now, units = "secs")
      all_times[[options$label]] <<- res
    }
  }
}))
knitr::opts_chunk$set(
  tidy = TRUE,
  tidy.opts = list(width.cutoff = 95),
  message = FALSE,
  warning = FALSE,
  fig.width = 10,
  time_it = TRUE
)
```


# Overview

```{r load, message = F, warning = F, echo = F}
library(tidyverse)
library(Seurat)
library(stImage)
library(patchwork)
library(reticulate)
use_condaenv(condaenv = "myenv", conda = "/home/wangy67/miniconda3/bin/conda")
library(tensorflow)
library(keras)

tstamp <- gsub("-", "", as.character(Sys.Date()))
```


# Prepare input file

```{r define, echo = F}
pre_path = "/data/cqs/ywang/Zhao_image/stImage"
proj_folder = "Adult_Mouse_Olfactory_Bulb"
workDir = paste(pre_path, "SpatialTranscriptomicsImage", "stImage", sep = "/")
h5_file = "Visium_Mouse_Olfactory_Bulb_filtered_feature_bc_matrix.h5"

data_path=paste(pre_path, proj_folder, sep = "/") #need filtered_feature_bc_matrix.h5 file and spatial folder
spatial_path = paste(data_path, "spatial", sep = "/")

imgFile=paste(spatial_path, "tissue_hires_image.png", sep = "/")
rawimg=paste(data_path, "Visium_Mouse_Olfactory_Bulb_image.tif", sep = "/")

#positionTableFile is 10X format, Columns: Tissue; Y,X,ImageY,ImageX
positionTableFile=paste(spatial_path, "tissue_positions_list.csv", sep = "/")

patchSize=200

```


# Extract features

```{r extract.feature, echo = F}
#require(jsonlite)
#scaleFactorFile=paste0(spatial_path,"/scalefactors_json.json")
#scaleFactor=fromJSON(scaleFactorFile)$tissue_hires_scalef
#
#positionTable=read.csv(positionTableFile, col.names = c("barcodes", "tissue", "row", "col", "imagerow", "imagecol"), as.is = TRUE, header=FALSE,row.names=1)
#positionTable=positionTable[which(positionTable[,1]==1),, drop = FALSE]
#positionTable=positionTable[,c(4:5)] #only need ImageX and ImageY

imageFeatures_raw=extract_features_Visium(spatial_path, rawImage = F, savePatchOnImage = paste0(proj_folder, "_rawpatch","_", tstamp, ".png"))
#write.csv(imageFeatures_raw,paste0(workDir,"/",proj_folder,"_features_raw_",tstamp,".csv"))

```

# load Image Feature into Seurat object

```{r load.data, echo = F}
#imageFeatures_raw <- read.csv(paste0(workDir,"/",proj_folder,"_features_raw_",tstamp,".csv"), row.names=1)

Adult_Mouse_Olfactory_Bulb_rawimage_obj <- LoadImageFeatureVisium(data_path, filename = h5_file,
                                  imageFeatures = imageFeatures_raw)

```

# Data analysis of Spatial matrix and ImageFeature matrix

```{r data.process, echo = F}
Adult_Mouse_Olfactory_Bulb_rawimage_obj <- MultimodalImageWorkflowVisium(Adult_Mouse_Olfactory_Bulb_rawimage_obj, normalizeMethod = "SCT", pcaDim_s=30, pcaDim_i=30, geneResolution=1.05, imageFeatureResolution=2.23, imageAndGeneResolution=1.2, MultimodalMethod = c("WNN", "MCIA", "tICA"))

#saveRDS(Adult_Mouse_Olfactory_Bulb_rawimage_obj, paste0(proj_folder, "_rawimage_object", tstamp, ".rds"))
```

# Visualization

## DimPlot

```{r DimPlot, fig.dim = c(12, 4), echo = F}
p1 <- DimPlot(Adult_Mouse_Olfactory_Bulb_rawimage_obj, reduction = 'st.umap', group.by = 'seurat_clusters', label = TRUE, 
              repel = TRUE, label.size = 2.5) + ggtitle("SCT") + NoLegend()
p2 <- DimPlot(Adult_Mouse_Olfactory_Bulb_rawimage_obj, reduction = 'if.umap', group.by = 'seurat_clusters', label = TRUE, 
              repel = TRUE, label.size = 2.5) + ggtitle("ImageFeature") + NoLegend()
p3 <- DimPlot(Adult_Mouse_Olfactory_Bulb_rawimage_obj, reduction = 'wnn.umap', label = TRUE, repel = TRUE, label.size = 2.5) + ggtitle("WNN") + NoLegend()

p1 + p2 + p3
```

## SpatialDimPlot

```{r SpatialDimPlot, fig.dim = c(12, 4), echo = F}
DefaultAssay(Adult_Mouse_Olfactory_Bulb_rawimage_obj) <- "Spatial"
p4 <- SpatialDimPlot(Adult_Mouse_Olfactory_Bulb_rawimage_obj, group.by = "SCT_snn_res.1.05", label = TRUE, label.box = F, label.size = 2) + ggtitle("SCT") & NoLegend()

DefaultAssay(Adult_Mouse_Olfactory_Bulb_rawimage_obj) <- "ImageFeature"
p5 <- SpatialDimPlot(Adult_Mouse_Olfactory_Bulb_rawimage_obj, group.by = "ImageFeature_snn_res.2.23", label = TRUE, label.box = F, label.size = 2) + ggtitle("ImageFeature") & NoLegend()

p6 <- SpatialDimPlot(Adult_Mouse_Olfactory_Bulb_rawimage_obj, group.by = "wsnn_res.1.2", label = TRUE, label.box = F, repel = TRUE, label.size = 2) + ggtitle("WNN") & NoLegend()

p7 <- SpatialDimPlot(Adult_Mouse_Olfactory_Bulb_rawimage_obj, group.by = "mcia_res.1.2", label = TRUE, label.box = F, repel = TRUE, label.size = 2) + ggtitle("MCIA") & NoLegend()

p8 <- SpatialDimPlot(Adult_Mouse_Olfactory_Bulb_rawimage_obj, group.by = "tica_res.1.2", label = TRUE, label.box = F, repel = TRUE, label.size = 2) + ggtitle("tICA") & NoLegend()

p4 + p5 + p6 + p7+ p8
```

## Image feature PCs

```{r imagefeaturepcs, fig.dim = c(20, 40), echo = F}
DefaultAssay(Adult_Mouse_Olfactory_Bulb_rawimage_obj) <- "ImageFeature"
Adult_Mouse_Olfactory_Bulb_rawimage_obj <- AddMetaData(object = Adult_Mouse_Olfactory_Bulb_rawimage_obj, metadata = as.data.frame(Adult_Mouse_Olfactory_Bulb_rawimage_obj@reductions$ipca@cell.embeddings))
p9 <- SpatialFeaturePlot(Adult_Mouse_Olfactory_Bulb_rawimage_obj, features = colnames(Adult_Mouse_Olfactory_Bulb_rawimage_obj@reductions$ipca@cell.embeddings), alpha = c(0.1, 1), ncol = 5)

```

## Weight of SCT and ImageFeature

```{r weight.plot, fig.dim = c(8, 4), echo = F}

p10 <- VlnPlot(Adult_Mouse_Olfactory_Bulb_rawimage_obj, features = "SCT.weight", group.by = 'wsnn_res.1.2', sort = TRUE, pt.size = 0.1) + ggtitle("SCT") +
  NoLegend()
p11<- VlnPlot(Adult_Mouse_Olfactory_Bulb_rawimage_obj, features = "ImageFeature.weight", group.by = 'wsnn_res.1.2', sort = TRUE, pt.size = 0.1) + ggtitle("ImageFeature") +
  NoLegend()
p10 + p11
```


<details>
  <summary>**Session Info**</summary>
```{r}
sessionInfo()
```
</details>
