---
title: "integrate spatial transcriptome and Image with stImage (HER2)"
output:
  html_document:
    theme: united
    df_print: kable
  pdf_document: default
date: 'Compiled: `r Sys.Date()`'
---

```{r setup, include=FALSE}
all_times <- list()  # store the time for each chunk
knitr::knit_hooks$set(time_it = local({
  now <- NULL
  function(before, options) {
    if (before) {
      now <<- Sys.time()
    } else {
      res <- difftime(Sys.time(), now, units = "secs")
      all_times[[options$label]] <<- res
    }
  }
}))
knitr::opts_chunk$set(
  tidy = TRUE,
  tidy.opts = list(width.cutoff = 95),
  message = FALSE,
  warning = FALSE,
  fig.width = 10,
  time_it = TRUE
)
```


# Overview

```{r install, message = F, warning = F, echo = F}

library(tidyverse)
library(Seurat)
library(stImage)
library(patchwork)
library(reticulate)
use_condaenv(condaenv = "myenv", conda = "/home/wangy67/miniconda3/bin/conda")

```

## Simulation data

### Pipeline Simple Test

```{r}

setwd("/scratch/cqs/zhaos/Spatial/simulation/")
clusterNum=6
repInd=0

   dataAFile = paste0("20220504_simulation_data_a_cluster",
                       clusterNum,
                       "_Rep",
                       repInd,
                       ".csv")
    dataBFile = paste0("20220504_simulation_data_b_cluster",
                       clusterNum,
                       "_Rep",
                       repInd,
                       ".csv")
    dataTrueLabelFile = paste0("20220504_simulation_label_true_cluster",
                               clusterNum,
                               "_Rep",
                               repInd,
                               ".csv")
    
    dataA = read.csv(dataAFile, header = FALSE)
    dataB = read.csv(dataBFile, header = FALSE)
    row.names(dataA) = paste0("Sample", 1:nrow(dataA))
    row.names(dataB) = paste0("Sample", 1:nrow(dataB))
    colnames(dataA) = paste0("Gene", 1:ncol(dataA))
    colnames(dataB) = paste0("ImageFeature", 1:ncol(dataB))
    
    dataTrueLabel = read.csv(dataTrueLabelFile, header = FALSE)
    dataTrueLabel = dataTrueLabel[, 1]
    names(dataTrueLabel) = row.names(dataA)

    dataCoordinate=addSimulationCoordinate(dataTrueLabel,dropRate=0)
    
    dataObjSimulation=LoadImageFeature(countTable = t(dataA),
              imageFeatures = (dataB), positionTable = dataCoordinate[,c("x","y")], project = paste0("Cluster",clusterNum,"Rep",repInd))
    dataObjSimulation = AddMetaData(dataObjSimulation, dataTrueLabel, col.name =
                                      "TrueLabel")    


dataObjSimulationPCA <- MultimodalPreProcess(dataObjSimulation,normalizeMethod = "SCT", DimReducMethod = "PCA",genePercentCut=0.05, imagePercentCut=0.05)
dataObjSimulationPCA=findSNNClusters(dataObjSimulationPCA,reduction="SCTPCA",nCluster=clusterNum)
checkARI(dataObjSimulationPCA)
dataObjSimulationPCA=findSNNClusters(dataObjSimulationPCA,reduction="ImageFeaturePCA",nCluster=clusterNum,resolutionMax=3)
checkARI(dataObjSimulationPCA)
dataObjSimulationPCA=MultiModalIntegrationVisium(dataObjSimulationPCA,MultimodalMethod="WNN",clusterNum=6)
checkARI(dataObjSimulationPCA,clusterColumnName=paste0("wnn_cluster",clusterNum))
 

dataObjSimulationSpatialPCA <- MultimodalPreProcess(dataObjSimulation,DimReducMethod = "SpatialPCA",  genePercentCut=0.05, imagePercentCut=0.05)
dataObjSimulationSpatialPCA=findSNNClusters(dataObjSimulationSpatialPCA,reduction="SCTSpatialPCA",nCluster=clusterNum,resolutionMax=3)
checkARI(dataObjSimulationSpatialPCA)
dataObjSimulationSpatialPCA=findSNNClusters(dataObjSimulationSpatialPCA,reduction="ImageFeatureSpatialPCA",nCluster=clusterNum,resolutionMax=3)
checkARI(dataObjSimulationSpatialPCA)


dataObjSimulationPCAGeneNormByImage=NormalizeGeneByImage(
  dataObjSimulationPCA,
  assay="SCT",dataSlot=c("data")) 
dataObjSimulationPCAGeneNormByImage=runDimReduc(dataObjSimulationPCAGeneNormByImage,assay="SCTNormalizedByImage")
dataObjSimulationPCAGeneNormByImage=findSNNClusters(dataObjSimulationPCAGeneNormByImage,reduction="SCTNormalizedByImagePCA",nCluster=clusterNum,resolutionMax=3)


dataObjSimulationPCAGenePCNormByImage=NormalizeGeneByImage(dataObjSimulationPCA, assay="SCT",geneDimReducName="SCTPCA") 
dataObjSimulationPCAGenePCNormByImage=findSNNClusters(dataObjSimulationPCAGenePCNormByImage,reduction="SCTPCANormalizedByImage",nCluster=clusterNum)


checkARI=function(dataObj,clusterColumnName="seurat_clusters") {
  clusterResult=as.character(dataObj@meta.data[[clusterColumnName]])
  print(paste0("Number of clusters identified: ",length(unique(clusterResult))))
  ariValue=adjustedRand(
      clusterResult,
      dataObj@meta.data$TrueLabel,
      randMethod = "HA"
    )
  return(ariValue)
}


checkARI(dataObjSimulationPCA)
checkARI(dataObjSimulationSpatialPCA)

checkARI(dataObjSimulationPCAGenePCNormByImage)
checkARI(dataObjSimulationPCAGeneNormByImage)



```




### Different number of clusters

```{r}

setwd("/scratch/cqs/zhaos/Spatial/simulation/")

source("~/source/stImage/R/MultimodalPreProcess.R")
source("~/source/stImage/R/MultimodalIntegrationVisium.R")

libray(clues)
ARIAll = NULL
for (clusterNum in c(6, 8, 10)) {
  #clusterNum=6
  for (repInd in 0:9) {
    dataAFile = paste0("20220504_simulation_data_a_cluster",
                       clusterNum,
                       "_Rep",
                       repInd,
                       ".csv")
    dataBFile = paste0("20220504_simulation_data_b_cluster",
                       clusterNum,
                       "_Rep",
                       repInd,
                       ".csv")
    dataTrueLabelFile = paste0("20220504_simulation_label_true_cluster",
                               clusterNum,
                               "_Rep",
                               repInd,
                               ".csv")
    
    dataA = read.csv(dataAFile, header = FALSE)
    dataB = read.csv(dataBFile, header = FALSE)
    row.names(dataA) = paste0("Sample", 1:nrow(dataA))
    row.names(dataB) = paste0("Sample", 1:nrow(dataB))
    colnames(dataA) = paste0("Gene", 1:ncol(dataA))
    colnames(dataB) = paste0("ImageFeature", 1:ncol(dataB))
    
    dataTrueLabel = read.csv(dataTrueLabelFile, header = FALSE)
    dataTrueLabel = dataTrueLabel[, 1]
    names(dataTrueLabel) = row.names(dataA)
    
    # dataObjSimulation <-
    #   CreateSeuratObject(counts = t(dataA), assay = "Spatial")
    # 
    # temp <- CreateAssayObject(counts = t(dataB))
    # dataObjSimulation[["ImageFeature"]] <- temp
    # dataObjSimulation = AddMetaData(dataObjSimulation, dataTrueLabel, col.name =
    #                                   "TrueLabel")
    
    
    
    dataCoordinate=addSimulationCoordinate(dataTrueLabel,dropRate=0)
    
    dataObjSimulation=LoadImageFeature(countTable = t(dataA),
              imageFeatures = (dataB), positionTable = dataCoordinate[,c("x","y")], project = paste0("Cluster",clusterNum,"Rep",repInd))
    dataObjSimulation = AddMetaData(dataObjSimulation, dataTrueLabel, col.name =
                                      "TrueLabel")
    
    #dataObjSimulation = MultimodalImageWorkflow10X(dataObjSimulation)
    dataObjSimulationPCA <- MultimodalPreProcess(dataObjSimulation,normalizeMethod = "SCT", DimReducMethod = "PCA",
                                                 geneResolution = 1.5,imageFeatureResolution=1.5)
    dataObjSimulationPCA <- MultiModalIntegrationVisium(dataObjSimulationPCA, 
                                                           normalizeMethod = "SCT",
                                                           DimReducMethod = "PCA",
                                                        MultimodalMethod="WNN")

    # vgg16_norm_gene_by_image <- normalizeGeneByImage(vggdataObjProcessed, coordinateNeighborN=6)
    # resnetgenePCs=t(resnetdataObjProcessed@reductions$pca@cell.embeddings[,1:nPCs])
    # resnet50_norm_genePCs_by_image <- normalizeGeneByImage(resnetdataObjProcessed, coordinateNeighborN=6, geneExp = resnetgenePCs)


    renorm_vggdataObjProcessed <- ReProcessAfterRenormByImage(vggdataObjProcessed,
                                                             normalizeMethod = "SCT",
                                                             renormbyimage = "GeneExp",
                                                             geneResolution=1.4,
                                                             imageFeatureResolution = 1.1,
                                                             imagePercentCut=0.1)

    
    dataObjSimulationSpatialPCA <- MultimodalPreProcess(dataObjSimulation,normalizeMethod = "SCT", DimReducMethod = "SpatialPCA",
                                                        geneResolution = 1.2,imageFeatureResolution=1.2)
    dataObjSimulationSpatialPCA <- MultiModalIntegrationVisium(dataObjSimulationSpatialPCA, 
                                                           normalizeMethod = "SCT",
                                                           DimReducMethod = "SpatialPCA",
                                                           MultimodalMethod="WNN")

    
    # p1 <- DimPlot(dataObjSimulation, reduction = 'st.umap', group.by = 'TrueLabel', label = TRUE,
    #             repel = TRUE, label.size = 2.5)
    # p2 <- DimPlot(dataObjSimulation, reduction = 'if.umap', group.by = 'TrueLabel', label = TRUE,
    #             repel = TRUE, label.size = 2.5)
    # p3 <- DimPlot(dataObjSimulation, reduction = 'wnn.umap', label = TRUE, repel = TRUE, label.size = 2.5, group.by = 'TrueLabel')
    # p1 + p2 + p3
    
    ARIGeneOnePCA = adjustedRand(
      as.character(dataObjSimulationPCA@meta.data$"SCT_snn_res.0.8"),
      dataObjSimulation@meta.data$TrueLabel,
      randMethod = "HA"
    )
    ARIImageOnePCA = adjustedRand(
      as.character(dataObjSimulationPCA@meta.data$"ImageFeature_snn_res.0.8"),
      dataObjSimulation@meta.data$TrueLabel,
      randMethod = "HA"
    )
    ARIIntegratedOnePCA = adjustedRand(
      as.character(dataObjSimulationPCA@meta.data$"wsnn_res.0.8"),
      dataObjSimulation@meta.data$TrueLabel,
      randMethod = "HA"
    )
    
    ARIGeneOneSpatialPCA = adjustedRand(
      as.character(dataObjSimulationSpatialPCA@meta.data$"st_spca_snn_res.0.8"),
      dataObjSimulationSpatialPCA@meta.data$TrueLabel,
      randMethod = "HA"
    )
    ARIImageOneSpatialPCA = adjustedRand(
      as.character(dataObjSimulationSpatialPCA@meta.data$"if_spca_snn_res.0.8"),
      dataObjSimulationSpatialPCA@meta.data$TrueLabel,
      randMethod = "HA"
    )
    ARIIntegratedOneSpatialPCA = adjustedRand(
      as.character(dataObjSimulationSpatialPCA@meta.data$"spca_wsnn_res.0.8"),
      dataObjSimulationSpatialPCA@meta.data$TrueLabel,
      randMethod = "HA"
    )
    
    ARIone = c(
      clusterNum = clusterNum,
      repInd = repInd,
      GenePCA = ARIGeneOnePCA,
      ImagePCA = ARIImageOnePCA,
      IntegratedPCA = ARIIntegratedOnePCA,
      GeneSpatialPCA = ARIGeneOneSpatialPCA,
      ImageSpatialPCA = ARIImageOneSpatialPCA,
      IntegratedSpatialPCA = ARIIntegratedOneSpatialPCA
    )
    ARIAll = rbind(ARIAll, ARIone)
  }
}
write.csv(ARIAll,"20220921_clusterNum_simulation_ARI.csv")


dataForPlot=data.frame(ARIAll[,c(1:5)]) %>% pivot_longer(
  names_to="Method",values_to = "HA",
  cols =c("GenePCA.HA" ,"ImagePCA.HA" ,"IntegratedPCA.HA")) %>%  
  group_by(clusterNum,Method) %>% summarise(
  HA.mean=mean(HA),
  HA.SD=sd(HA)
  )

p<- ggplot(dataForPlot, aes(x=factor(clusterNum), y=HA.mean, fill=Method)) + 
  geom_bar(stat="identity", color="black", 
           position=position_dodge()) +
  geom_errorbar(aes(ymin=HA.mean-HA.SD, ymax=HA.mean+HA.SD), width=.2,
                 position=position_dodge(.9)) 
plot(p)


dataForPlot=data.frame(ARIAll[,c(1:2,6:8)]) %>% pivot_longer(
  names_to="Method",values_to = "HA",
  cols =c("GeneSpatialPCA.HA" ,"ImageSpatialPCA.HA" ,"IntegratedSpatialPCA.HA")) %>%  
  group_by(clusterNum,Method) %>% summarise(
  HA.mean=mean(HA),
  HA.SD=sd(HA)
  )

p<- ggplot(dataForPlot, aes(x=factor(clusterNum), y=HA.mean, fill=Method)) + 
  geom_bar(stat="identity", color="black", 
           position=position_dodge()) +
  geom_errorbar(aes(ymin=HA.mean-HA.SD, ymax=HA.mean+HA.SD), width=.2,
                 position=position_dodge(.9)) 
plot(p)




# dataA=read.csv("/scratch/cqs/zhaos/Spatial/simulation/20220504_simulation_data_a.csv",header=FALSE)
# dataB=read.csv("/scratch/cqs/zhaos/Spatial/simulation/20220504_simulation_data_b.csv",header=FALSE)
# dim(dataA)
# dim(dataB)
# row.names(dataA)=paste0("Sample",1:nrow(dataA))
# row.names(dataB)=paste0("Sample",1:nrow(dataB))
# colnames(dataA)=paste0("Gene",1:ncol(dataA))
# colnames(dataB)=paste0("ImageFeature",1:ncol(dataB))
# 
# 
# dataTrueLabel=read.csv("/scratch/cqs/zhaos/Spatial/simulation/20220504_simulation_label_true.csv",header=FALSE)
# dataTrueLabel=dataTrueLabel[,1]
# table(dataTrueLabel)
# names(dataTrueLabel)=row.names(dataA)
# 
# dataObj <- CreateSeuratObject(counts = t(dataA),assay="Spatial")
# Assays(dataObj)
# 
# temp <- CreateAssayObject(counts = t(dataB))
# dataObj[["ImageFeature"]] <- temp
# 
# dataObj=AddMetaData(dataObj,dataTrueLabel,col.name="TrueLabel")
# 
# dataObjSimulation=MultimodalImageWorkflow10X(dataObj)
# 
# p1 <- DimPlot(dataObjSimulation, reduction = 'st.umap', group.by = 'TrueLabel', label = TRUE, 
#               repel = TRUE, label.size = 2.5) 
# p2 <- DimPlot(dataObjSimulation, reduction = 'if.umap', group.by = 'TrueLabel', label = TRUE, 
#               repel = TRUE, label.size = 2.5) 
# p3 <- DimPlot(dataObjSimulation, reduction = 'wnn.umap', label = TRUE, repel = TRUE, label.size = 2.5, group.by = 'TrueLabel') 
# 
# p1 + p2 + p3
# 
# 
# 
# adjustedRand(as.character(dataObjSimulation@meta.data$"wsnn_res.0.8"), dataObjSimulation@meta.data$TrueLabel)


```



## Add spatial information to simulation data

### Make simulation spatial data method 1

```{r}

library(ggplot2)

#library(spatstat)
#?rpoispp

makeSpatialData=function(nNotSpatial=100,nSpatial=list(30),
                         xSpatialRange=list(c(0.2,0.4)),ySpatialRange=list(c(0.2,0.4))) {
  xNotSpatial=runif(nNotSpatial)
  yNotSpatial=runif(nNotSpatial)
  
  xSpatial=list()
  ySpatial=list()
  for (i in 1:length(xSpatialRange)) {
      xSpatial[[i]]=runif(nSpatial[[i]],min=xSpatialRange[[i]][1],max=xSpatialRange[[i]][2])
      ySpatial[[i]]=runif(nSpatial[[i]],min=ySpatialRange[[i]][1],max=ySpatialRange[[i]][2])
  }
  
  dataOut=data.frame(x=xNotSpatial,y=yNotSpatial,spatial="NotSpatial")
  for (j in 1:length(xSpatial)) {
    temp=data.frame(x=xSpatial[[j]],y=ySpatial[[j]],spatial=paste0("Spatial",j))
    dataOut=rbind(dataOut,temp)
  }
  
  return(dataOut)
}


nSpatial=list(100,100,100)
spatialSimulationData=makeSpatialData(nNotSpatial=700,
                            nSpatial=nSpatial,
                            xSpatialRange=list(
                              c(0.2,0.4),
                              c(0.6,0.7),
                              c(0.6,1)
                              ),
                           ySpatialRange=list(
                              c(0.2,0.4),
                              c(0.1,0.15),
                              c(0.6,1)
                              )
                            )
ggplot(spatialSimulationData,aes(x=x,y=y,color=spatial))+geom_point()


```


### Make simulation spatial data method 2: mutinormal distribution

```{r}


library(mvtnorm)

clusterN=8
spotNPerCluster=50


coordinateWidth=sqrt(clusterN*spotNPerCluster)
coordinateHeight=coordinateWidth
spotN=coordinateWidth*coordinateHeight

coordinateMatrix=NULL
for (i in 1:coordinateWidth) {
  coordinateMatrix=rbind(coordinateMatrix,data.frame(x=i,y=1:coordinateHeight))
}
coordinateMatrix=as.matrix(coordinateMatrix)

centerPosList=list()
for (i in 1:clusterN) {
  centerPosList=c(centerPosList,list(c(sample(1:coordinateWidth,1),sample(1:coordinateHeight,1))))
}

centerDensityList=list()
for (i in 1:length(centerPosList)){
  centerDensityList[[i]]=dmvnorm(x=coordinateMatrix, mean=centerPosList[[i]])
}
names(centerDensityList)=paste0("C",1:length(centerPosList))
centerDensityListNorm=t(apply(sapply(centerDensityList,function(x) x/sum(x)),1,function(y) y/sum(y)))

spotsFromClustersInd=sample(1:spotN,spotN,replace = FALSE)
clusterAssignedCount=structure(c(rep(0,ncol(centerDensityListNorm))),names=colnames(centerDensityListNorm))

spotCluster=rep(NA,spotN)
for (i in 1:length(spotsFromClustersInd)) {

  spotInd=spotsFromClustersInd[i]
  spotNormProb=centerDensityListNorm[spotInd,]
  finshedClusterNames=names(which(clusterAssignedCount>=spotNPerCluster))
  if (length(finshedClusterNames)>0) {
    spotNormProb[finshedClusterNames]=0
  }
  assignedCluster=sample(names(clusterAssignedCount),1,prob=spotNormProb)

  spotCluster[spotInd]=assignedCluster
  clusterAssignedCount[assignedCluster]=clusterAssignedCount[assignedCluster]+1

}

coordinateMatrixOut=data.frame(coordinateMatrix,Cluster=spotCluster)

ggplot(coordinateMatrixOut,aes(x=x,y=y,color=Cluster))+geom_point()


addSimulationCoordinate=function(sampleCluster,dropRate=0) {
  
  sampleN=length(sampleCluster)
  clusterN=length(unique(sampleCluster))
  clusterNames=names(table(sampleCluster))
  spotNPerCluster=table(sampleCluster)
  spotNPerClusterMax=max(spotNPerCluster)

  coordinateWidth=as.integer(sqrt(clusterN*spotNPerClusterMax))+1
  coordinateHeight=coordinateWidth
  spotN=coordinateWidth*coordinateHeight

  coordinateMatrix=NULL
  for (i in 1:coordinateWidth) {
    coordinateMatrix=rbind(coordinateMatrix,data.frame(x=i,y=1:coordinateHeight))
  }
  coordinateMatrix=as.matrix(coordinateMatrix)

centerPosList=list()
for (i in 1:clusterN) {
  centerPosList=c(centerPosList,list(c(sample(1:coordinateWidth,1),sample(1:coordinateHeight,1))))
}

centerDensityList=list()
for (i in 1:length(centerPosList)){
  centerDensityList[[i]]=dmvnorm(x=coordinateMatrix, mean=centerPosList[[i]])
}
names(centerDensityList)=clusterNames
centerDensityListNorm=t(apply(sapply(centerDensityList,function(x) x/sum(x)),1,function(y) y/sum(y)))

if (dropRate>0) {
  dropSpotN=as.integer(sampleN*dropRate)
  spotsNotFromClustersInd=sample(1:spotN,dropSpotN,replace = FALSE)
  spotsNotFromClustersIndCluster=sample(clusterNames,length(spotsNotFromClustersInd),replace=TRUE)
  
  spotsNotFromClustersIndAssign=data.frame(coordinateMatrix[spotsNotFromClustersInd,],CoordinateCluster=spotsNotFromClustersIndCluster)
  
  temp=table(spotsNotFromClustersIndCluster)
  spotNPerCluster[names(temp)]=spotNPerCluster[names(temp)]-temp
  
  spotsFromClustersInd=sample(setdiff(1:spotN,spotsNotFromClustersInd),sampleN-dropSpotN,replace = FALSE)
} else {
  spotsNotFromClustersIndAssign=NULL
  spotsFromClustersInd=sample(1:spotN,sampleN,replace = FALSE)
}

#clusterAssignedCount=structure(c(rep(0,clusterN)),names=names(sampleClusterNameToCoordinateClusterName))

spotsFromClustersIndAssign=data.frame()
for (i in 1:length(spotsFromClustersInd)) {
  spotInd=spotsFromClustersInd[i]
  spotNormProb=centerDensityListNorm[spotInd,]
  finshedClusterNames=names(which((spotNPerCluster==0)))
  if (length(finshedClusterNames)>0) {
    spotNormProb[finshedClusterNames]=0
  }
  assignedCluster=sample(names(spotNormProb),1,prob=spotNormProb)

  temp=data.frame(coordinateMatrix[spotInd,,drop=FALSE],CoordinateCluster=assignedCluster)
  spotsFromClustersIndAssign=rbind(spotsFromClustersIndAssign,temp)
  
  spotNPerCluster[assignedCluster]=spotNPerCluster[assignedCluster]-1
}

spotsCoordinateMatrixOut=data.frame(SampleCluster=as.character(sampleCluster),x=0,y=0,CoordinateCluster="")
row.names(spotsCoordinateMatrixOut)=names(sampleCluster)
temp=rbind(spotsFromClustersIndAssign,spotsNotFromClustersIndAssign)
for (i in as.character(unique(sampleCluster))) {
  spotsCoordinateMatrixOut[which(spotsCoordinateMatrixOut$SampleCluster==i),-1]=  temp[which(temp$CoordinateCluster==i),]
}

#ggplot(spotsCoordinateMatrixOut,aes(x=x,y=y,color=SampleCluster))+geom_point()
  return(spotsCoordinateMatrixOut)
  
}



```





### Add simulation spatial data to simulation omics data for analysis

```{r}
library(Seurat)
library(tidyverse)

setwd("/scratch/cqs/zhaos/Spatial/simulation/")

# for (clusterNum in c(6, 8, 10)) {
#   #clusterNum=6
#   for (repInd in 0:9) {
clusterNum=6
repInd=0
    dataAFile = paste0("20220504_simulation_data_a_cluster",
                       clusterNum,
                       "_Rep",
                       repInd,
                       ".csv")
    dataBFile = paste0("20220504_simulation_data_b_cluster",
                       clusterNum,
                       "_Rep",
                       repInd,
                       ".csv")
    dataTrueLabelFile = paste0("20220504_simulation_label_true_cluster",
                               clusterNum,
                               "_Rep",
                               repInd,
                               ".csv")
    
    dataA = read.csv(dataAFile, header = FALSE)
    dataB = read.csv(dataBFile, header = FALSE)
    row.names(dataA) = paste0("Sample", 1:nrow(dataA))
    row.names(dataB) = paste0("Sample", 1:nrow(dataB))
    colnames(dataA) = paste0("Gene", 1:ncol(dataA))
    colnames(dataB) = paste0("ImageFeature", 1:ncol(dataB))
    
    dataTrueLabel = read.csv(dataTrueLabelFile, header = FALSE)
    dataTrueLabel = dataTrueLabel[, 1]
    names(dataTrueLabel) = row.names(dataA)
    
    dataObjSimulation <-
      CreateSeuratObject(counts = t(dataA), assay = "Spatial")
    
    temp <- CreateAssayObject(counts = t(dataB))
    dataObjSimulation[["ImageFeature"]] <- temp
    dataObjSimulation = AddMetaData(dataObjSimulation, dataTrueLabel, col.name =
                                      "TrueLabel")
    dataObjSimulation = MultimodalImageWorkflow10X(dataObjSimulation)
    

  table(dataTrueLabel)  
    

  
  

spatialSimulationData$Sample=NA
spatialClusters=c(0,1,2)
for (i in 1:length(spatialClusters)) {
  nSpatialOne=nSpatial[[i]]
  saptialSamplesOne=names(which(dataTrueLabel==spatialClusters[i]))[1:nSpatialOne]
  spatialSimulationData$Sample[which(spatialSimulationData$spatial==paste0("Spatial",(i+1)))]=saptialSamplesOne
}
#assign rest samples to non-saptial
spatialSimulationData$Sample[which(is.na(spatialSimulationData$Sample))]=setdiff(names(dataTrueLabel),spatialSimulationData$Sample)
spatialSimulationData$TrueLabel=factor(dataTrueLabel[spatialSimulationData$Sample])


#add spatial information to spatialSimulationData
positionTable=spatialSimulationData[,c("x","y")]
row.names(positionTable)=spatialSimulationData$Sample
dataObjSimulation[['images']] <- new(Class = 'SlideSeq', assay = "Spatial", coordinates = positionTable)

  
ggplot(spatialSimulationData,aes(x=x,y=y,color=TrueLabel))+geom_point()






#   }
# }
```


## Run software

```{r}

dataObj=LoadImageFeature(countTable = t(countTable),
              imageFeatures = imageFeatures, positionTable = positionTable, project = sampleName)

PDACB_dataObj=readRDS(objectRdsName)
PDACB_SPCA_dataObjProcessed <- MultimodalPreProcess(PDACB_dataObj,
                                         normalizeMethod = "SCT",
                                         DimReducMethod = "SpatialPCA",
                                         geneResolution=0.8,
                                         imageFeatureResolution = 0.8,
                                         imagePercentCut=0.2)
PDACB_SPCA_dataObjProcessed <- MultiModalIntegrationVisium(PDACB_SPCA_dataObjProcessed, 
                                                normalizeMethod = "SCT",
                                                DimReducMethod = "SpatialPCA",
                                                imageAndGeneResolution=0.3,
                                                MultimodalMethod = "WNN")
saveRDS(PDACB_SPCA_dataObjProcessed, paste0(workDir,basename(objectRdsName), ".SPCA.processed.rds"))


#extract spatialPCA result
reduction="GeneSPatialPCA"

```




